[env:esp32doit-devkit-v1]
platform = espressif32@6.4.0  #  ȶ  棬    ESP32-D0WD-V3
board = esp32doit-devkit-v1   #  뿪     ͺ   ȫƥ 䣨ȷ ϰ忨  ESP32-D0WD-V3   ģ 
framework = arduino           #      ȷ  ESP32    Arduino
upload_port = COM8            #  ص㣺ȷ   豸        ESP32 Ķ˿   COM8           ˿ڣ 
upload_speed = 115200
; ESP32 Flash       ã     ƥ  Ӳ                ޷       
board_build.flash_mode = dio
board_build.flash_freq = 40m
board_build.flash_size = 4mb
board_build.bootloader = bootloader_dio_40m.bin
board_build.partitions = default.csv
;    ڼ     ã    ϴ  ˿ һ £      ͻ  
monitor_port = COM8
monitor_speed = 115200
;       ǿ Ƽ   Arduino               δ   ص  µı       ȱʧ  
lib_deps = 
    arduino-libraries/ArduinoOTA@^1.0.9  #     OTA ⣨Arduino  ܱر   
    ESP32-Helper-Libraries  #   ѡ      ESP32    ĸ     
;             ־          Ų    ʧ  ԭ  
build_flags = 
    -Wno-error=maybe-uninitialized  #  ر  ޹ؾ  棬 ۽    Ĵ   
    -D ARDUINO_ESP32_DOIT_DEVKIT_V1  #     忨 ꣬ƥ    